version: '2'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    restart: always
    depends_on:
      - redis
    environment:
      DB_ADDR: 'redis:6379'
      TG_TOKEN: '2036532268:AAEu_zBS-gP5LLPOfBI8AffiZgS-1UwqlRg'
      CHANNEL_ID: '-1001262825216'
      TIKTOK_USERNAME: 'fantomatus'
      TIKTOK_SEC_USER_ID: 'MS4wLjABAAAAZ_R2Sf8Sf4XcldiSW03Xs510zLO1st2TbN-3I-KgbWxbRPRs7eOMFYlMtNDAVDsm'
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
